### ISSUE TITLE
if action is triggered by pr event short-sha returns main shortened sha instead of branch

### ISSUE THREAD

**Issue by SergiiShapoval** [benjlevesque/short-sha#16]
we are using the checkout command with ref input:
```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: branch_name # PR source branch name
```

but after such checkout, current action uses SHA from main instead of the last commit SHA

it looks like we need to use `context.event.pull_request.head.sha` instead of `context.sha` in https://github.com/benjlevesque/short-sha/blob/v2.2/src/main.ts

WDYT?
